/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class FmrCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraRadioTK
     */
    public FmrCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2Corpo = new javax.swing.JPanel();
        lblmenos = new javax.swing.JLabel();
        lblMais = new javax.swing.JLabel();
        lblVezes = new javax.swing.JLabel();
        lblDividido = new javax.swing.JLabel();
        rBtnSubtracao = new javax.swing.JRadioButton();
        rBtnSoma = new javax.swing.JRadioButton();
        rBtnMultiplicacao = new javax.swing.JRadioButton();
        rBtnDivisao = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jPanelTelaDisplay = new javax.swing.JPanel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        lblIgual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDigite = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCULADORA");
        setBackground(new java.awt.Color(51, 204, 255));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 55, 122));

        jPanel2Corpo.setBackground(new java.awt.Color(35, 121, 225));

        lblmenos.setBackground(new java.awt.Color(204, 204, 255));
        lblmenos.setFont(new java.awt.Font("Arial Black", 1, 60)); // NOI18N
        lblmenos.setForeground(new java.awt.Color(224, 171, 74));
        lblmenos.setText("_");

        lblMais.setBackground(new java.awt.Color(204, 204, 255));
        lblMais.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lblMais.setForeground(new java.awt.Color(224, 171, 74));
        lblMais.setText("+");

        lblVezes.setBackground(new java.awt.Color(204, 204, 255));
        lblVezes.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        lblVezes.setForeground(new java.awt.Color(224, 171, 74));
        lblVezes.setText("x");

        lblDividido.setBackground(new java.awt.Color(204, 204, 255));
        lblDividido.setFont(new java.awt.Font("Arial", 0, 65)); // NOI18N
        lblDividido.setForeground(new java.awt.Color(224, 171, 74));
        lblDividido.setText("÷");

        rBtnSubtracao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rBtnSubtracao.setForeground(new java.awt.Color(224, 171, 74));
        rBtnSubtracao.setText("SUBTRAÇÃO");
        rBtnSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnSubtracaoActionPerformed(evt);
            }
        });

        rBtnSoma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rBtnSoma.setForeground(new java.awt.Color(224, 171, 74));
        rBtnSoma.setText("SOMA");
        rBtnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnSomaActionPerformed(evt);
            }
        });

        rBtnMultiplicacao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rBtnMultiplicacao.setForeground(new java.awt.Color(224, 171, 74));
        rBtnMultiplicacao.setText("MULTIPLICAÇÃO");
        rBtnMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMultiplicacaoActionPerformed(evt);
            }
        });

        rBtnDivisao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rBtnDivisao.setForeground(new java.awt.Color(224, 171, 74));
        rBtnDivisao.setText("DIVISÃO");
        rBtnDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnDivisaoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanelTelaDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum2ActionPerformed(evt);
            }
        });

        lblIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIgual.setText("=");

        jLabel3.setBackground(new java.awt.Color(242, 240, 239));
        jLabel3.setText("lblResultado");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelTelaDisplayLayout = new javax.swing.GroupLayout(jPanelTelaDisplay);
        jPanelTelaDisplay.setLayout(jPanelTelaDisplayLayout);
        jPanelTelaDisplayLayout.setHorizontalGroup(
            jPanelTelaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaDisplayLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIgual)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTelaDisplayLayout.setVerticalGroup(
            jPanelTelaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaDisplayLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanelTelaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIgual)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        lblDigite.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDigite.setForeground(new java.awt.Color(255, 255, 255));
        lblDigite.setText("Digite dois números:");

        javax.swing.GroupLayout jPanel2CorpoLayout = new javax.swing.GroupLayout(jPanel2Corpo);
        jPanel2Corpo.setLayout(jPanel2CorpoLayout);
        jPanel2CorpoLayout.setHorizontalGroup(
            jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2CorpoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                                .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                                        .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblMais)
                                                .addComponent(lblmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                                                .addComponent(lblDividido)
                                                .addGap(17, 17, 17)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rBtnSubtracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rBtnSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rBtnDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rBtnMultiplicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2CorpoLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblVezes)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPanelTelaDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                                .addComponent(lblDigite)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        jPanel2CorpoLayout.setVerticalGroup(
            jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2CorpoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDigite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTelaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(rBtnSubtracao)))
                .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                        .addGroup(jPanel2CorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMais, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnSoma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDividido, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(jPanel2CorpoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rBtnDivisao)
                        .addGap(29, 29, 29)
                        .addComponent(rBtnMultiplicacao)
                        .addGap(34, 34, 34)))
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel2Corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2Corpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnDivisaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnDivisaoActionPerformed

    private void rBtnMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMultiplicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMultiplicacaoActionPerformed

    private void rBtnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnSomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnSomaActionPerformed

    private void rBtnSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnSubtracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnSubtracaoActionPerformed

    private void txtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNum2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (rBtnSoma.isSelected())
        {
            try{
            double x = Double.parseDouble(fieldNum1.getText());
            double y = Double.parseDouble(fieldNum2.getText());
            
            double soma = x + y;
            
            lblResposta.setText("Soma: "+soma);
            fieldNum1.setText("");
            fieldNum2.setText("");
        }
        catch(NumberFormatException erro){
            JOptionPane.showMessageDialog(this, "Digite um número válido");
            
            fieldNum1.setText("");
            fieldNum2.setText("");
            }
            }
                
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FmrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FmrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FmrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FmrCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FmrCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2Corpo;
    private javax.swing.JPanel jPanelTelaDisplay;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblDigite;
    private javax.swing.JLabel lblDividido;
    private javax.swing.JLabel lblIgual;
    private javax.swing.JLabel lblMais;
    private javax.swing.JLabel lblVezes;
    private javax.swing.JLabel lblmenos;
    private javax.swing.JRadioButton rBtnDivisao;
    private javax.swing.JRadioButton rBtnMultiplicacao;
    private javax.swing.JRadioButton rBtnSoma;
    private javax.swing.JRadioButton rBtnSubtracao;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
