

package view;
import javax.swing.JOptionPane;
import model.Cidade;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
 
public class FrmCadCidade extends javax.swing.JInternalFrame {
    List<Cidade> lista = new ArrayList<Cidade>();
    int contId = 1;
    int indice = 0;
    

    
    /**
     * Creates new form FrmCadCidade
     */
    public FrmCadCidade() {
        initComponents();
        txtId.setEnabled(false); //Desabilitei o botão pro usuário não editar ele. Não quero editar ID pois é chave primária
        preencherTabela();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblUF = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        lblCep = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        cbxUF = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        cadCidade = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCidades = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 255, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder());
        setClosable(true);
        setForeground(java.awt.Color.cyan);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Cidades");
        setToolTipText("");

        lblId.setText("Id:");

        lblNome.setText("Nome:");

        lblUF.setText("Estado");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblCep.setText("CEP:");

        txtId.setText("1");
        txtId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtId.setCaretColor(new java.awt.Color(102, 255, 51));

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--", "AC", "AL", "AP ", "AM ", "BA ", "CE ", "DF ", "ES ", "GO ", "MA ", "MT ", "MS ", "MG ", "PA ", "PB ", "PR", "PE ", "PI ", "RJ ", "RN ", "RS ", "RO ", "RR ", "SC" }));
        cbxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUFActionPerformed(evt);
            }
        });

        cadCidade.setBackground(new java.awt.Color(255, 255, 255));
        cadCidade.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        cadCidade.setText("Cadastro de Cidades");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setBackground(new java.awt.Color(255, 255, 204));
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        btnNovo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnNovoKeyReleased(evt);
            }
        });

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tblCidades.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "UF", "CEP"
            }
        ));
        tblCidades.setSelectionBackground(new java.awt.Color(102, 204, 255));
        tblCidades.setSelectionForeground(new java.awt.Color(153, 153, 255));
        tblCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCidadesMouseClicked(evt);
            }
        });
        tblCidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCidadesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblCidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior)
                    .addComponent(btnSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProximo)
                    .addComponent(btnEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUltimo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnExcluir)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUF)
                                .addGap(15, 15, 15)
                                .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblCep)
                                .addGap(18, 18, 18)
                                .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblId)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cadCidade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(cadCidade)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUF)
                    .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrimeiro)
                            .addComponent(btnAnterior))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvar)
                            .addComponent(btnNovo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUltimo)
                            .addComponent(btnProximo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir)
                            .addComponent(btnEditar))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUFActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Cidade cidade = new Cidade(); //startou variável cidade que foi criada com base no modelo cidade.
            
        cidade.id   = Integer.parseInt(txtId.getText());
        cidade.nome = txtNome.getText();
        cidade.uf   = cbxUF.getSelectedItem().toString();
        cidade.cep  = txtCep.getText();
        
        lista.add(cidade);
        
        JOptionPane.showMessageDialog(this, "Cidade salva com sucesso!!");
        
        indice = lista.size()-1;
        mostrarDados();
        preencherTabela();
       
       
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (!lista.isEmpty()){
            int recId = Integer.parseInt(txtId.getText());  //RecId é a variável para receber o Id. Ele vai percorrer a lista para saber qual o Id atual e salvar no recId;
        for(int i=0; i<lista.size(); i++)
        {
            if(lista.get(i).id == recId)
            {   
                int op = JOptionPane.showConfirmDialog(this,"Tem certeza que deseja excluir a cidade: "+lista.get(i).nome +"?","Exclusão",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
                if (op == 0){
                    if(!lista.isEmpty())
                    {
                    lista.remove(i);
                    preencherTabela();
                    JOptionPane.showMessageDialog(this,"Removido com sucesso.");
                    if(lista.isEmpty())
                    {
                        txtId.setText("");
                        txtNome.setText("");
                        cbxUF.setSelectedItem("--selecione--");
                        txtCep.setText("");
                        
                    }
                }else{
                        indice=lista.size()-1;
                        mostrarDados();
                        
                    }
                   
                }
            }
        }
    }
        else{ JOptionPane.showMessageDialog(this,"Você desistiu de excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
       contId++;
       txtId.setText(""+contId);
       txtNome.setText("");
       cbxUF.setSelectedItem("--Selecionar--");
       txtCep.setText("");
       preencherTabela();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
       //txtId.setText(""+lista.get(lista.size()-1).id);
       //txtNome.setText(lista.get(lista.size()-1).nome);
       //cbxUF.setSelectedItem(lista.get(lista.size()-1).uf);
       //txtCep.setText(lista.get(lista.size()-1).cep);
       indice = lista.size() -1;
        mostrarDados();
        btnPrimeiro.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnUltimo.setEnabled(false);
        btnProximo.setEnabled(false);
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed

       indice=0;
       mostrarDados();
        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnUltimo.setEnabled(true);
        btnProximo.setEnabled(true);

    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed

        if (indice > 0){
            indice--;
        btnUltimo.setEnabled(true);
        btnProximo.setEnabled(true);
       }else
        {
        JOptionPane.showMessageDialog(this, "Você já está no primeiro registro.","Atenção", JOptionPane.WARNING_MESSAGE);
        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnUltimo.setEnabled(true);
        btnProximo.setEnabled(true);

        }
        mostrarDados();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if(indice<lista.size()-1){
            indice++;
            btnAnterior.setEnabled(true);
            btnUltimo.setEnabled(true);
        }else
        {
        JOptionPane.showMessageDialog(this, "Você já está no último registro.","Atenção", JOptionPane.WARNING_MESSAGE);
        btnUltimo.setEnabled(false);
        btnProximo.setEnabled(false);
        btnAnterior.setEnabled(true);
        btnUltimo.setEnabled(true);
        }
            
        mostrarDados();
        
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int recId = Integer.parseInt(txtId.getText());
        for(int i=0; i<lista.size(); i++){
            if(lista.get(i).id == recId)
            {
                lista.get(i).nome = txtNome.getText();
                lista.get(i).uf = cbxUF.getSelectedItem().toString();
                lista.get(i).cep = txtCep.getText();
                JOptionPane.showMessageDialog(this, "A cidade de "+lista.get(i).nome+" foi editada com sucesso!");
                preencherTabela();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCidadesMouseClicked
        preencherFormByTable();
    }//GEN-LAST:event_tblCidadesMouseClicked

    private void tblCidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCidadesKeyReleased
        if(evt.getKeyCode() == 38 || evt.getKeyCode() == 40){
            preencherFormByTable();
        }
    }//GEN-LAST:event_tblCidadesKeyReleased

    private void btnNovoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnNovoKeyReleased
         if(evt.getKeyCode() == 78){
       contId++;
       txtId.setText(""+contId);
       txtNome.setText("");
       cbxUF.setSelectedItem("--Selecionar--");
       txtCep.setText("");
       preencherTabela();
             
         }
    }//GEN-LAST:event_btnNovoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cadCidade;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTable tblCidades;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
public void mostrarDados()
{
       txtId.setText(""+lista.get(indice).id);
       txtNome.setText(lista.get(indice).nome);
       cbxUF.setSelectedItem(lista.get(indice).uf);
       txtCep.setText(lista.get(indice).cep);
}
public void preencherTabela(){
    tblCidades.getColumnModel().getColumn(0).setPreferredWidth(WIDTH); //PreferredWidth é a largura medida em pixels
    tblCidades.getColumnModel().getColumn(1).setPreferredWidth(50); // Ps: Muda esse valor pra Width depois só pra testar
    tblCidades.getColumnModel().getColumn(2).setPreferredWidth(2);
    tblCidades.getColumnModel().getColumn(3).setPreferredWidth(20);
    
    double b = 5.5;
    int a = (int)b; // Isso é chamado de casting. colocar o (int) antes do número que você quer converter
    
    DefaultTableModel modelo = (DefaultTableModel)tblCidades.getModel();
    modelo.setNumRows(0); //Limpar a tabela
    
    for(int i=0;i<lista.size();i++){
        modelo.addRow(new Object[]{
            lista.get(i).id,
            lista.get(i).nome,
            lista.get(i).uf,
            lista.get(i).cep
        });
        }
    }

public void preencherFormByTable(){
    
    int lineChoose = tblCidades.getSelectedRow();
    txtId.setText(tblCidades.getValueAt(lineChoose, 0).toString());
    txtNome.setText(tblCidades.getValueAt(lineChoose, 1).toString());
    cbxUF.setSelectedItem(tblCidades.getValueAt(lineChoose,2));
    txtCep.setText(tblCidades.getValueAt(lineChoose,3).toString());
    
    
}

}
