/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import dao.DaoCidade;
import javax.swing.JOptionPane;
import model.Cidade;
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author IFG
 */
public class FrmCadCidade extends javax.swing.JInternalFrame {
    List<Cidade> lista = new ArrayList<Cidade>();
    DaoCidade sara = new DaoCidade();
    int contid = 0;
    int indice = 0;


    /**
     * Creates new form FrmCadCidade
     */
    public FrmCadCidade() {
        initComponents();
        txtId.setEditable(false);
        lista = sara.getCidades();
        if(lista.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Não tem registro na tabela cidade");
        }else
        {
            mostrarDadosTela();
            preencherTabela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloCadCidade = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCidades = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblTituloCadCidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloCadCidade.setText("Cadastro de Cidades");

        lblId.setText("ID:");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        lblNome.setText("Nome:");

        lblUF.setText("UF:");

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecionar--", "AC", "AL", "AM", "DF", "GO", "PA", "RO", "MG", "TO", " ", " " }));

        lblCep.setText("Cep:");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tblCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "UF", "CEP"
            }
        ));
        tblCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCidadesMouseClicked(evt);
            }
        });
        tblCidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblCidadesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblCidades);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnNovo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnEditar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnSalvar)))
                        .addGap(36, 36, 36)
                        .addComponent(btnExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblNome))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCep, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblUF, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnPrimeiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTituloCadCidade)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAnterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUltimo)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTituloCadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCep))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrimeiro)
                    .addComponent(btnProximo)
                    .addComponent(btnUltimo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Cidade cidade = new Cidade();
        
        //cidade.id = Integer.parseInt(txtId.getText());
        cidade.nome = txtNome.getText();
        cidade.uf = cbxUF.getSelectedItem().toString();//entende como item por isso o "to string" para conversão para string
        cidade.cep = txtCep.getText();
        //Não vou salvar mais na lista irei salvar direto no BD
        //lista.add(cidade);
        sara.salvarCidade(cidade);
        
        lista = sara.getCidades();
        
        JOptionPane.showMessageDialog(this, "Cidade salva com sucesso!!!");
        
        txtId.setText(""+lista.get(0).id);
        txtNome.setText(lista.get(0).nome);
        cbxUF.setSelectedItem(lista.get(0).uf);
        txtCep.setText(lista.get(0).cep);
        
        preencherTabela();


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       Cidade cidade = new Cidade();
       
        
        int recid = Integer.parseInt(txtId.getText());
        for(int i = 0; i < lista.size(); i++)
        {
            if(lista.get(i).id == recid)
            {
                lista.get(i).nome = txtNome.getText();
                lista.get(i).uf = cbxUF.getSelectedItem().toString();
                lista.get(i).cep = txtCep.getText();
                JOptionPane.showMessageDialog(this, "A cidade de"+ lista.get(i).nome +" foi editada com sucesso");
                preencherTabela();
            }
        }

        
       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(!lista.isEmpty()){
        int recid = Integer.parseInt(txtId.getText());
        for(int i = 0; i < lista.size(); i++)
        {
            if(lista.get(i).id == recid)
            {
                int op = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir a cidade: "+lista.get(i).nome+" ?", "Exclusão", JOptionPane.YES_OPTION,JOptionPane.WARNING_MESSAGE);
                        if(op == 0)
                        {
                            //if(!lista.isEmpty())
                            //{
                                lista.remove(i);
                                preencherTabela();
                                
                                if(!lista.isEmpty())
                                {
                                    txtId.setText("");
                                    txtNome.setText("");
                                    cbxUF.setSelectedItem("--Selecionar--");
                                    txtCep.setText("");
                                }else{
                                    indice = lista.size()-1;
                                    mostrarDadosTela();
                              
                                //}
                            }//else{
                                //JOptionPane.showMessageDialog(this, "Não exixtem dados para serem excluidos");
                            }
                            
                        }//else{
                          //  JOptionPane.showMessageDialog(this, "Você desistiu de excluir");
                        //}
                
            }
        }
        
    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        contid++;
        txtId.setText(""+contid);
        txtNome.setText("");
        cbxUF.setSelectedItem("--Selecionar--");
        txtCep.setText("");

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        indice = 0;
        mostrarDadosTela();
        btnPrimeiro.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnProximo.setEnabled(true);
        btnUltimo.setEnabled(true);

    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        indice = lista.size()-1;
        mostrarDadosTela();
        btnPrimeiro.setEnabled(true);
        btnAnterior.setEnabled(true);
        btnProximo.setEnabled(false);
        btnUltimo.setEnabled(false);

    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
         if(indice>0){
            indice--;
            btnUltimo.setEnabled(true);
            btnProximo.setEnabled(true);
           
        }else{
            JOptionPane.showMessageDialog(this, "Você já está no primeiro Registro", "Atenção", JOptionPane.WARNING_MESSAGE);
            btnPrimeiro.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnUltimo.setEnabled(true);
            btnProximo.setEnabled(true);
        }
         mostrarDadosTela();

    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if(indice<lista.size()-1)
        {
            indice ++;
            btnAnterior.setEnabled(true);
            btnPrimeiro.setEnabled(true);
        }else
        {
            JOptionPane.showMessageDialog(this, "Você já está no ultimo Registro", "Atenção",JOptionPane.WARNING_MESSAGE);
            btnProximo.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnAnterior.setEnabled(true);
            btnPrimeiro.setEnabled(true);
        }
        
        mostrarDadosTela();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void tblCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCidadesMouseClicked
        preencherFormByTable();
    }//GEN-LAST:event_tblCidadesMouseClicked

    private void tblCidadesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCidadesKeyReleased
        if(evt.getKeyCode()== 38 || evt.getKeyCode()== 40){
            preencherFormByTable();
        }
    }//GEN-LAST:event_tblCidadesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTituloCadCidade;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTable tblCidades;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
public void mostrarDadosTela() 
{
        txtId.setText(""+lista.get(indice).id);
        txtNome.setText(lista.get(indice).nome);
        cbxUF.setSelectedItem(lista.get(indice).uf);
        txtCep.setText(lista.get(indice).cep);
    }

public void preencherTabela(){
    
    tblCidades.getColumnModel().getColumn(0).setPreferredWidth(10);
    tblCidades.getColumnModel().getColumn(1).setPreferredWidth(150);
    tblCidades.getColumnModel().getColumn(2).setPreferredWidth(10);
    tblCidades.getColumnModel().getColumn(3).setPreferredWidth(20);
    
    DefaultTableModel modelo = (DefaultTableModel)tblCidades.getModel();
    modelo.setNumRows(0);//Limpar tabela
    
    for(int i = 0; i < lista.size();i++){
        modelo.addRow(new Object[]{
            lista.get(i).id,
            lista.get(i).nome,
            lista.get(i).uf,
            lista.get(i).cep
        
        });
     }
    }

public void preencherFormByTable(){
    
    int linechoose = tblCidades.getSelectedRow();
    txtId.setText(tblCidades.getValueAt(linechoose, 0).toString());
    txtNome.setText(tblCidades.getValueAt(linechoose, 1).toString());
    cbxUF.setSelectedItem(tblCidades.getValueAt(linechoose,2));
    txtCep.setText(tblCidades.getValueAt(linechoose, 3).toString());
    
    }
}
